dist: bionic
language: rust

env:
  global:
    - CRATE_NAME=abstalg

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

before_install:
  - rustup self update

script:
  - cargo build --verbose
  - cargo test -- --nocapture

sudo: false

notifications:
  email: false
